### ISSUE TITLE
Is there way to use static images in styles folder?

### ISSUE THREAD

**Issue by xquezme** [davezuko/react-redux-starter-kit#369]
/styles/pattern.scss
```scss
.pattern {
  background-image: './static/pattern.png';
}
```
/components/SomeComponent.scss

```scss
.someStyle {
  composes: pattern from '../styles/pattern.scss';
}
```
Work as expected (btw, only with [precss](https://github.com/jonathantneal/precss)), but as global: 
 ```scss
:global {
  .pattern {
    background-image: './static/pattern.png';
  }
}
```
Can't resolve file.

**Comment by davezuko** [comment]
Since static files are served from the root of the app, what if you just tried `/pattern.png`? I can't test this locally right now, but that's my first guess.

**Comment by SimonSelg** [comment]
@davezuko : Using just `background-image: url(pattern.png)` won't work because url-loader will complain because it can't find pattern.png at the root of the src folder or in the same directory (possible improvement here: let url-loader ignore url(..) expressions that point to the static folder if that's possible).

What you can do is: Put the image in a folder, not the static folder (because it's for assets that are not required anywhere in the source code, and all url(...) expression in scss files are processed by webpack), let's assume you put it in "src/images".

Then:

`/styles/pattern.scss`

```css
.pattern {
  background-image: url('images/pattern.jpg');
}
```
`/components/SomeComponent.scss`

```css
.someStyle {
  composes: pattern from 'styles/pattern.scss';
  height: 50px;
  width: 50px;
}
```

That works, because now url-loader will be able to locate the image correctly and bundle it correctly.
