### ISSUE TITLE
Where to serve fonts from?

### ISSUE THREAD

**Issue by hamishtaplin** [davezuko/react-redux-starter-kit#403]
Although you can probably just serve fonts from the static directory, there's some config for fonts in webpack but I don't seem to be able to get it to pick any up. Is there some specific place they need to be?

**Comment by alexmuro** [comment]
+1

**Comment by SimonSelg** [comment]
I'll post you a snipped from my project as soon as I get home.

**Comment by SimonSelg** [comment]
Sorry, i totally forgot about this one. You probably figured it out by now, but just in case this is how I'd do it:

Suppose you have your font roboto.woff in `~src/assets/fonts/`, and you want to make it available in your app, so you can use it with `font-family: roboto`.

Then you have to include it w/ `@font-face` somewhere in your code. A good place would be `~src/styles/core.css`:

```css
@import 'base';

// make roboto available
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: local('Roboto'), local('Roboto-Regular'), url(../assets/fonts/roboto.woff) format('woff');
}
```

Webpack will recognize that your css depends on `~src/assets/fonts/roboto.woff` and therefore bundle the roboto.woff correctly.

Hope this helps. If not, just let me know what's still unclear.
