### ISSUE TITLE
possible scss reloading issue, changes to core.scss dont update in the browser

### ISSUE THREAD

**Issue by mikedevita** [davezuko/react-redux-starter-kit#533]
in my `src/styles/core.scss` I added the following......

```css
.no-gutter {
  padding-right:0;
  padding-left:0;
}
.no-gutter > [class*='col-'] {
    padding-right:0;
    padding-left:0;
}
.no-left-gutter > [class*='col-'] {
    padding-left:0;
}

.no-right-gutter > [class*='col-'] {
    padding-right:0;
}

.itemsList .row {
  padding-bottom: 4px;
}
.itemsList {
  height:100px;
  max-height: 100px;
  overflow-y: scroll;
}
```

I'd expect on save or even save and refresh to see these styles take affect but they aren't. What am i missing? I am using the latest merge for bootstrap-sass loader. I would ultimately like to load this into a scss file in my components folder and just import it and have them take effect without having to do something like `styles[itemsList...`
