### ISSUE TITLE
Sass parent selector in Webpack

### ISSUE THREAD

**Issue by cascornelissen** [davezuko/react-redux-starter-kit#560]
When using the Sass parent selector `&` at the end of a selector the CSS that Webpack outputs won't work correctly.

The following Scss for example...
```scss
.main {
    padding-left: 100px;

    .app.is-full & {
        padding-left: 0;
    }
}
```

Gets transformed into this CSS:
```css
.main {
    padding-left: 100px;
}
.app__app___3f8DN.app__is-full___r-A8L .main {
    padding-left: 0;
}
```

Which won't work since the element doesn't have that class... I think this is a problem with Webpack but I can't really find anything about it so I'm hoping you can help me get started on why this is happening and how to fix it.

**Comment by davezuko** [comment]
Are you not using CSS modules? If not, and you're writing the class names out manually in your JSX, make sure to disable this option: https://github.com/davezuko/react-redux-starter-kit/blob/master/config/_base.js#L28

If this is actually a totally different problem let me know and I'll try to do a better job at grasping the issue.

**Comment by cascornelissen** [comment]
I am also using CSS modules, I though I could use both? I also have some global styles (like the one in my original post) that I would like to include though...

**Comment by davezuko** [comment]
So I'm a little bit confused about the generated CSS, though maybe I'll just have to try to reproduce it locally before commenting further. I'd _expect_ that:

```scss
.main {
    padding-left: 100px;

    .app.is-full & {
        padding-left: 0;
    }
}
```

would be transformed to:

```
.<file>__main__<hash> {
  padding-left: 100px;
}

.<file>__main__<hash> .<file>__app-is-full__<hash> .<file>__main__<hash> {
  padding-left: 0;
}
```

I've honestly never seen the parent selector used like that, so I'm a bit confused as to the intention of the code, which is making this a little difficult to process.

**Comment by davezuko** [comment]
Then again, I'm not a huge user of CSS modules so I could be totally off base.

**Comment by cascornelissen** [comment]
Note that the above Scss is located in `src/styles/`, so this file is not used as a CSS module. I do, however, have some views that do have seperate CSS modules (and include 1 global `_settings.scss` with variables).

So I would think that it would be transformed into the following because these are the actual classes on the elements if I view them in Chrome DevTools.

```css
.main {
    padding-left: 100px;
}
.app.is-full .main {
    padding-left: 0;
}
```

Regarding the parent selector: all it does it get the current selector (all nested parent selectors combined) and replaces the `&` with that value. It can be used [anywhere](http://thesassway.com/intermediate/referencing-parent-selectors-using-ampersand).
