### ISSUE TITLE
How can I use :global block of css modules under components directory

### ISSUE THREAD

**Issue by choyongjoon** [davezuko/react-redux-starter-kit#567]
I manage my components like this
```
components
├── SideBar
│   ├── SideBar.js
│   ├── SideBar.scss
...
```
I want to use :global block in SideBar.scss. But it doesn't work at all.
In src/styles/core.css, it works well.

Should I change webpack.config.js?

**Comment by davezuko** [comment]
Hmmmm, I will take a look, not sure to be honest.

**Comment by chenfanggm** [comment]
@choyongjoon May I ask what is :global block?

**Comment by thangngoc89** [comment]
@chenfanggm it's css-modules https://github.com/css-modules/css-modules

**Comment by chenfanggm** [comment]
@thangngoc89 Thanks :)

**Comment by davezuko** [comment]
I can't reproduce this. Just so you know, CSS modules don't automatically hot reload, so you'll either have to write your own HMR accept handler where the style is imported or reload the page. If you can confirm that you are still in fact having this problem I'd be happy to re-open and continue investigating.

On the latest version of master, I added the following to `HomeView.scss`:

```scss
.counter {
  font-weight: bold;
}

.counter--green {
  composes: counter;
  color: rgb(25,200,25);
}

.duck {
  display: block;
  width: 100%;
  margin-top: 1.5rem;
}

:global {
  html, body {
    background: red !important;
  }
}
```

And it worked without issue. If you are having other problems my best guess is that it's CSS modules related and not necessarily related to this starter kit, but again I can't say much for sure without a working example to repro the issue.
