### ISSUE TITLE
Issues with CSS animations

### ISSUE THREAD

**Issue by zsherman** [davezuko/react-redux-starter-kit#584]
Have no idea if this has to do with the project setup (I attempted to rule out everything), but I noticed that keyframe animations don't appear to run when rendered inside components. Has anyone else had this issue or have any thoughts on what might be the cause?

**Comment by zsherman** [comment]
As a dead-simple experiment, try rendering this from a component: http://jsfiddle.net/allusis/dQQcX/.

**Comment by davezuko** [comment]
Where are you adding these styles? I just edited `HomeView.js`'s Double Async button as follows:

```js
<button className={classes.foo} onClick={this.props.doubleAsync}>
  Double (Async)
</button>
```

And added the following styles to `HomeView.scss`:

```scss
.foo {
  width:100px;
  height:100px;
  background:red;
  position:relative;
  animation:mymove 5s infinite;
}

@keyframes mymove {
  from {top:0px;}
  to {top:200px;}
}
```

And it worked in Chrome, Firefox, and Safari (I don't have access to IE at the moment).

![foo](https://cloud.githubusercontent.com/assets/6439050/13204239/b84ba6ac-d898-11e5-825a-322dd576e59c.gif)

**Comment by zsherman** [comment]
So I'm actually importing the styles from a separate partial in `core.scss` – not sure why that'd be different.

**Comment by zsherman** [comment]
Potentially related http://stackoverflow.com/questions/31070033/broken-css-keyframe-animations-when-using-webpacks-css-loader-with-uglifyjs-plu.

**Comment by JuoCode** [comment]
@zsherman  By default, `cssnano` is enabled with [lots of options](http://cssnano.co/optimisations/); I think your problem may be caused by certain option, and you can disable anyone in `build/webpack.config.js` like below:

```
webpackConfig.postcss = [
  cssnano({
    // ......
  })
];

```

**Comment by macnibblet** [comment]
I'm having the exact same reason, the minified css has a differet name for the keyframe and the component uses the "unobfuscated" version. 

![Component](http://caps.interactivesolutions.se/ss/anto/ac6b2d.png)
![CSS File](http://caps.interactivesolutions.se/ss/anto/9d089c.png)

**Comment by macnibblet** [comment]
And this is with cssnano completely disabled, so something is renaming the css class in the css file generation but the component className does not get updated.

**Comment by macnibblet** [comment]
I have fixed it, but i'm guessing it's just a hack, so a proper solution would be good.
Anyway change this line
https://github.com/davezuko/react-redux-starter-kit/blob/master/build/webpack.config.js#L173
With
`'localIdentName=[local]'`

**Comment by davezuko** [comment]
I feel like this is an issue with CSS modules and not with this project, but I'm not knowledgable enough to know for sure.

**Comment by davezuko** [comment]
I feel like this is a limitation of CSS modules, since there literally is nothing out of the ordinary that we're doing with CSS modules. See: https://css-modules.github.io/webpack-demo/

```css
.root {
  padding: 20px 10px;
}

.ball {
  composes: bounce from "shared/styles/animations.css";
  width: 40px;
  height: 40px;
  border-radius: 20px;
  background: rebeccapurple;
}

// share/styles/animations.css
@keyframes bounce {
  33% { transform: translateY(-20px); }
  66% { transform: translateY(0px); }
}

.bounce {
  animation: bounce 1s infinite ease-in-out;
}
```

**Comment by macnibblet** [comment]
core.scss
```scss
 @mixin spinner($size: 25px, $spinnerColor: 255, $borderSize: 3px) {
    display: block;
    height: $size;
    width: $size;
    margin: 10px auto;
    animation: rotation .7s infinite linear;
    border-left: $borderSize solid rgba($spinnerColor,$spinnerColor,$spinnerColor,.3);
    border-right: $borderSize solid rgba($spinnerColor,$spinnerColor,$spinnerColor,.3);
    border-bottom: $borderSize solid rgba($spinnerColor,$spinnerColor,$spinnerColor,.3);
    border-top: $borderSize solid rgba($spinnerColor,$spinnerColor,$spinnerColor,.9);
    border-radius:100%;
  }

  .spinner {
    @include spinner(50px, 150, 5px);
  }

  @-webkit-keyframes rotation {
    from {-webkit-transform: rotate(0deg);}
    to {-webkit-transform: rotate(359deg);}
  }

  @-moz-keyframes rotation {
    from {-moz-transform: rotate(0deg);}
    to {-moz-transform: rotate(359deg);}
  }

  @-o-keyframes rotation {
    from {-o-transform: rotate(0deg);}
    to {-o-transform: rotate(359deg);}
  }

  @keyframes rotation {
    from {transform: rotate(0deg);}
    to {transform: rotate(359deg);}
  }

  @mixin clearfix {
    &:after {
      content: "";
      display: table;
      clear: both;
    }
  }

  @import 'spinner-button';
```

spinner-button.scss
```scss
.spinner-button {
  position:relative;
  .spinner-text {
    display: block;
  }
  .spinner-element {
    display: none;

    position: absolute;
    top: 0;
    left: 0;
    border-radius: 5px;
    width: 100%;
    height: 100%;

    span {
      @include spinner;
    }
  }
  &.show {
    .spinner-text {
      color: transparent;
    }
    .spinner-element {
      display: block;
    }
  }
}
```

I'm guessing i'm doing something wrong and should be import my scss into react somehow according to https://github.com/css-modules/css-modules#css-modules ?
