### ISSUE TITLE
Multiple CSS Classes with CSS Modules.

### ISSUE THREAD

**Issue by ACregan** [davezuko/react-redux-starter-kit#747]
I have a simple list item menu, each with its own unique icon which I have styled using background-image. At any given time one of these items is the 'active' item and has additional styles to indicate this state however I cannot seem to get css modules to include both styles at the same time. 

## example JSX

```js
import React, {PropTypes} from 'react'
import styles from './portfolioitem.scss'
export class PortfolioItem extends React.Component {

  render () {

    const stylee = styles[this.props.label]

    if (this.props.activeItem == this.props.label){
      const stylee = styles[this.props.label] + ' ' + styles.activeitem
    }else{
      const stylee = styles[this.props.label]
    }

    return (
      <li className={stylee}>
        {this.props.title}
      </li>
    )
  }
}

export default PortfolioItem
```

example SCSS

```scss
li {
  &.tdcbitworks {
background:url('some/url/image.png') no-repeat;
  }
  &.activeitem {
    background: mediumpurple;
  }
}
```

EDIT: Sorry I cant seem to get jsx to work with the code tool on github

**Comment by grahamlyus** [comment]
I think your problem maybe that your are redefining `const stylee` again inside the if statements. Try:
```
let stylee = styles[this.props.label]

if (this.props.activeItem == this.props.label){
  stylee = stylee +' ' + styles.activeitem
}
```
Alternatively, look at the classnames package for a more common way of solving these kinds of things: https://www.npmjs.com/package/classnames

**Comment by ACregan** [comment]
Thanks for getting back to me. Your suggestion on using let instead of const didnt work but I'll try the classNames module tomorrow and see how that works out. Thanks you.

Keep up the great work. Cheers.

**Comment by davezuko** [comment]
What if you try just using the classes themselves without prefixing them with the `li` tag name?

```scss
.tdcbitworks {
  background:url('some/url/image.png') no-repeat;
}
.activeitem {
  background: mediumpurple;
}
```

```js
render () {
  const classes = styles[this.props.label]

  // ...
}
```
